name: '${project.name}'
main: '${project.groupId}.${plugin.main}'
version: '${project.version}'
api-version: '${plugin.api-version}'
libraries:
  - 'net.kyori:adventure-platform-bukkit:${versions.adventure-platform-bukkit}'
  - 'net.kyori:adventure-text-minimessage:${versions.adventure}'
  - 'net.kyori:adventure-text-serializer-legacy:${versions.adventure}'
  - 'net.kyori:adventure-text-serializer-plain:${versions.adventure}'
